# -*- coding: utf-8 -*-
"""DataAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15rsPX1f5d_88SwnV-3gbDTwkWMwDO3cn

#Comparative Analysis

**Sensitivity of RUSLE Soil Loss Estimates to LS Factor Formulation in Madagascar**

This notebook contains the full statistical and spatial analysis for my thesis. The LS factor rasters (BL, F1, F2), the three RUSLE soil loss rasters and the four input factor rasters (R, K, LS, C) were all computed beforehand in Google Earth Engine and then imported into ArcGIS Pro as `.tif` files. It runs locally in `arcpy` + `pandas` + `scipy`.

Strucutre:

1. Setup and raster loading
2. Pixel-wise extraction into a pandas dataframe using `PixelBlockCollection`
3. Slope stratification into 4 classes (<9%, 9–22%, 22–55%, >55%)
4. Summary statistics per method per slope class
5. Boxplots of LS factor distribution per slope class
6. empirical cumulative distribution functions (eCDFs)
7. Kolmogorov–Smirnov tests (global + per slope class)
8. Difference calculations between methods
9. Spearman rank correlation and coefficient of variation for the RUSLE input factors (Table 2)
10. Slope dependent line plot of mean LS factor (Figure 2)
11. Hotspot binary rasters + combination map + Jaccard similarity
12. Hotspot area per method and per population density class
13. Areal distribution of RUSLE soil loss classes

All paths point to the UZH group share `S:/group/ess_demand4restoration/bachelorThesisMarlena`. The analysis was run in the ArcGIS Pro `python` environment (3.11) so that `arcpy` works.

## 1. Setup

Imports and arcpy environment. The `Spatial` extension is needed for the `arcpy.sa` module (raster algebra, Con, Raster, etc.).
"""

import arcpy
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

from arcpy.sa import *
from arcpy.ia import PixelBlockCollection
from scipy import stats

arcpy.env.overwriteOutput = True
arcpy.env.workspace = r"S:\group\ess_demand4restoration\bachelorThesisMarlena"

arcpy.CheckOutExtension("Spatial")

"""## 2. Raster paths

All input rasters come pre-aligned to the same grid (UTM Zone 38S, EPSG:32738, 30 m cell size, snapped to the preprocessed DEM). The slope raster is in degrees and gets converted to percent later.

- `lsbl`, `lsf1`, `lsf2_nearing_true` — the three LS factor rasters (BL, F1, F2)
- `blloss_clip`, `F1loss_clip`, `F2los_clip` — the three RUSLE soil loss rasters
- `dem_slope_deg` — slope in degrees, from the preprocessed (sink-filled) DEM
"""

# Slope raster (in degrees, will be converted to % later)
slope_path = r"\\geofiles.d.uzh.ch\private\mbaril\windows\Documents\ArcGIS\Projects\Dem_preprocessing\dem_slope_deg"

# LS factor rasters
ls_baseline_path = r"S:\group\ess_demand4restoration\bachelorThesisMarlena\lsbl"
ls_v1_path       = r"S:\group\ess_demand4restoration\bachelorThesisMarlena\lsf1"
ls_v2_path       = r"S:\group\ess_demand4restoration\bachelorThesisMarlena\lsf2_nearing_true.tif"

# RUSLE soil loss rasters (computed in GEE, clipped to AOI)
ru_bl = "blloss_clip"
ru_v1 = "F1loss_clip"
ru_v2 = "F2los_clip"

# RUSLE input factor rasters (for the input factor analysis, Table 2)
r_path  = r"S:\group\ess_demand4restoration\bachelorThesisMarlena\R_factor.tif"
k_path  = r"S:\group\ess_demand4restoration\bachelorThesisMarlena\K_factor.tif"
c_path  = r"S:\group\ess_demand4restoration\bachelorThesisMarlena\C_factor.tif"

# Population density raster (WorldPop 2020, 1km)
pop_path = r"S:\group\ess_demand4restoration\bachelorThesisMarlena\worldpop_2020_1km.tif"

# Quick check that all rasters align (same extent, same cell size, same CRS)
slope_r       = arcpy.Raster(slope_path)
ls_baseline_r = arcpy.Raster(ls_baseline_path)
ls_v1_r       = arcpy.Raster(ls_v1_path)
ls_v2_r       = arcpy.Raster(ls_v2_path)

rasters = {
    "slope":       slope_r,
    "ls_baseline": ls_baseline_r,
    "ls_v1":       ls_v1_r,
    "ls_v2":       ls_v2_r,
}

for name, ras in rasters.items():
    print(f"{name}")
    print("  extent:", ras.extent)
    print("  width:", ras.width, "  height:", ras.height)
    print("  cell size:", ras.meanCellWidth, "x", ras.meanCellHeight)
    print("  CRS:", ras.spatialReference.name)
    print()

"""## 3. Pixel-wise extraction with `PixelBlockCollection`

The full rasters at 30m for the whole of Madagascar are way too big to load into memory in one go. `PixelBlockCollection` iterates over the rasters in spatially contiguous 512×512 blocks, so i can extract the pixel values block by block, drop the NoData cells, and append the valid ones into a pandas dataframe.

The `overlay_type="INTERSECTION"` makes sure we only get cells where ALL the rasters have valid data — this is important because the AOI mask, water bodies and the soil loss rasters all introduce some NaNs in slightly different places.

This step is the slow one (took ~25 min on the UZH share). After it finishes i save the result as a parquet file so i don't have to rerun it every time.
"""

raster_list = [
    slope_r,
    ls_baseline_r,
    ls_v1_r,
    ls_v2_r,
]

block_size = (512, 512)

pbc = PixelBlockCollection(
    raster_list,
    pixel_block_size=block_size,
    overlay_type="INTERSECTION",
    nodata_to_values=np.nan,
)

print("Number of blocks (y, x):", pbc.size)

# Test on a single block to make sure things look right
test_block = pbc[0, 41]

slope_block = np.squeeze(test_block[0].getData()).astype("float64")
ls_b_block  = np.squeeze(test_block[1].getData()).astype("float64")
ls_v1_block = np.squeeze(test_block[2].getData()).astype("float64")
ls_v2_block = np.squeeze(test_block[3].getData()).astype("float64")

for name, arr in [
    ("slope", slope_block),
    ("ls_b",  ls_b_block),
    ("ls_v1", ls_v1_block),
    ("ls_v2", ls_v2_block),
]:
    print(name, arr.shape, arr.dtype, "min =", np.nanmin(arr), "max =", np.nanmax(arr))

"""loop in block  collection->  dataframe."""

df_list = []

number_blocks_y, number_blocks_x = pbc.size

for by in range(number_blocks_y):
    print(f"Processing block row {by + 1} of {number_blocks_y}")

    for bx in range(number_blocks_x):
        block_list = pbc[by, bx]

        slope_block = np.squeeze(block_list[0].getData()).astype("float64")
        ls_b_block  = np.squeeze(block_list[1].getData()).astype("float64")
        ls_v1_block = np.squeeze(block_list[2].getData()).astype("float64")
        ls_v2_block = np.squeeze(block_list[3].getData()).astype("float64")

        valid = (
            ~np.isnan(slope_block) &
            ~np.isnan(ls_b_block) &
            ~np.isnan(ls_v1_block) &
            ~np.isnan(ls_v2_block)
        )

        if valid.sum() == 0:
            continue

        block_df = pd.DataFrame({
            "slope_deg":   slope_block[valid].ravel(),
            "ls_baseline": ls_b_block[valid].ravel(),
            "ls_v1":       ls_v1_block[valid].ravel(),
            "ls_v2":       ls_v2_block[valid].ravel(),
        })

        df_list.append(block_df)

df = pd.concat(df_list, ignore_index=True)

print(df.head())
print("shape:", df.shape)

# Save intermediate to parquet so we never have to rerun the block extraction
out_parquet = r"S:\group\ess_demand4restoration\bachelorThesisMarlena\full_analysis_tableupdate.parquet"
df.to_parquet(out_parquet, index=False)
print("Saved:", out_parquet)

"""## 4. Slope stratification

The slope raster comes out of ArcGIS in degrees. For the analysis i need it in % because that's what the slope class thresholds in the literature (9%, 22%, 55%) are defined in. The conversion is `slope_pct = tan(slope_deg) * 100`.

The four slope classes come straight from the math of the slope-steepness equations:
- **<9%** — both McCool branches active; the low-slope branch
- **9–22%** — McCool high-slope branch starts, Nearing still fits McCool
- **22–55%** — Nearing diverges from McCool, fitted on Liu et al. (1994) data
- **>55%** — outside the empirical calibration range of any S factor formulation
"""

# Convert slope from degrees to %
df["slope_pct"] = np.tan(np.deg2rad(df["slope_deg"])) * 100

bins = [0, 9, 22, 55, np.inf]
labels = ["<9%", "9–22%", "22–55%", ">55%"]

df["slope_class"] = pd.cut(
    df["slope_pct"],
    bins=bins,
    labels=labels,
    right=False,
)

print(df["slope_class"].value_counts().sort_index())

# Save
out_parquet = r"S:\group\ess_demand4restoration\bachelorThesisMarlena\full_analysis_table_slopeclassesupd.parquet"
df.to_parquet(out_parquet, index=False)
print("Saved processed file:", out_parquet)

"""## 5. Summary statistics

These are the numbers reported in **Table 1** of the thesis (whole-area stats per method) and in the per-slope-class results in Section 5.1.
"""

# Whole-area statistics per method (= Table 1 in the thesis)
stats_ls = df[["ls_baseline", "ls_v1", "ls_v2"]].agg([
    "min", "max", "mean", "std", "median",
])

print(stats_ls)

# Per slope class
summary_ls = df.groupby("slope_class", observed=False)[
    ["ls_baseline", "ls_v1", "ls_v2"]
].agg(["count", "median", "mean", "std", "min", "max"])

with pd.option_context("display.max_columns", None, "display.width", 200):
    print(summary_ls)

# Quartiles per slope class
quantiles = df.groupby("slope_class", observed=False)[
    ["ls_baseline", "ls_v1", "ls_v2"]
].quantile([0.25, 0.5, 0.75]).unstack()

with pd.option_context("display.max_columns", None, "display.width", 200):
    print(quantiles)

# 5th and 95th percentiles for the whole study area (used for Q0.95 column in Table 1)
percentiles_ls = {}
for col in ["ls_baseline", "ls_v1", "ls_v2"]:
    percentiles_ls[col] = df[col].quantile([0.05, 0.25, 0.5, 0.75, 0.95])
percentiles_ls = pd.DataFrame(percentiles_ls)
print(percentiles_ls)

"""## 6. Absolute and relative differences between methods

Pixel-wise differences are what feed into the difference maps in Figure 6. Absolute is more interpretable on the maps (units of LS factor), relative is useful as a sanity check.

`ad_` = absolute difference, `rd_` = relative difference (%).
"""

# Absolute differences
df["ad_b_v1"]  = np.abs(df["ls_v1"] - df["ls_baseline"])
df["ad_b_v2"]  = np.abs(df["ls_v2"] - df["ls_baseline"])
df["ad_v1_v2"] = np.abs(df["ls_v2"] - df["ls_v1"])

diff_summary = df.groupby("slope_class", observed=False)[
    ["ad_b_v1", "ad_b_v2", "ad_v1_v2"]
].median()

print(diff_summary)

# Relative differences (add tiny epsilon to avoid divide-by-zero on flat cells)
df["rd_b_v1"]  = 100 * (df["ls_v1"] - df["ls_baseline"]) / (df["ls_baseline"] + 1e-12)
df["rd_b_v2"]  = 100 * (df["ls_v2"] - df["ls_baseline"]) / (df["ls_baseline"] + 1e-12)
df["rd_v2_v1"] = 100 * (df["ls_v2"] - df["ls_v1"])       / (df["ls_v1"] + 1e-12)

agreement_rel = df.groupby("slope_class", observed=False)[
    ["rd_b_v1", "rd_b_v2", "rd_v2_v1"]
].median()

with pd.option_context("display.max_columns", None, "display.width", 200):
    print(agreement_rel)

"""## 7. Boxplots of LS factor per slope class (Figure 3)

4panel boxplot, one panel per slope class, three boxes per panel (BL, F1, F2). Different y-axis per panel

"""

methods = ["ls_baseline", "ls_v1", "ls_v2"]
classes = ["<9%", "9–22%", "22–55%", ">55%"]

class_colors = {
    "<9%":    "#d9d9d9",
    "9–22%":  "#bdbdbd",
    "22–55%": "#969696",
    ">55%":   "#636363",
}

plt.rcParams.update({
    "font.size":       11,
    "axes.labelsize":  12,
    "axes.titlesize":  12,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
    "figure.dpi":      300,
    "savefig.dpi":     300,
    "axes.linewidth":  0.8,
    "lines.linewidth": 1.0,
    "font.family":     "serif",
})

fig, axes = plt.subplots(1, 4, figsize=(14, 4.2), sharey=False)

for ax, sc in zip(axes, classes):
    stats_list = []
    for method in methods:
        vals = df.loc[df["slope_class"] == sc, method].dropna().to_numpy()

        q1, med, q3 = np.percentile(vals, [25, 50, 75])
        iqr = q3 - q1
        low_bound  = q1 - 1.5 * iqr
        high_bound = q3 + 1.5 * iqr

        whislo = vals[vals >= low_bound].min()
        whishi = vals[vals <= high_bound].max()

        stats_list.append({
            "label":  method.replace("ls_", "").replace("_", " "),
            "med":    med,
            "q1":     q1,
            "q3":     q3,
            "whislo": whislo,
            "whishi": whishi,
            "fliers": [],
        })

    artists = ax.bxp(
        stats_list,
        positions=np.arange(1, len(methods) + 1),
        widths=0.55,
        patch_artist=True,
        showfliers=False,
        medianprops=dict(color="black", linewidth=1.2),
        whiskerprops=dict(color="black", linewidth=0.9),
        capprops=dict(color="black", linewidth=0.9),
        boxprops=dict(edgecolor="black", linewidth=0.9),
    )

    for box in artists["boxes"]:
        box.set_facecolor(class_colors[sc])
        box.set_alpha(0.9)

    n_pixels = (df["slope_class"] == sc).sum()
    area_pct = 100 * n_pixels / len(df)
    ax.set_title(f"({chr(97 + classes.index(sc))}) {sc} slope\nArea = {area_pct:.1f}%")
    ax.set_xticks(np.arange(1, len(methods) + 1))
    ax.set_xticklabels(["BL", "F1", "F2"])
    ax.grid(axis="y", linestyle="--", linewidth=0.5, alpha=0.5)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

axes[0].set_ylabel("LS factor (-)")
fig.supxlabel("Method", y=0.04)

plt.tight_layout()
fig.savefig(r"W:\ls_boxplots_paraupd.png",
            dpi=600, bbox_inches="tight", facecolor="white")
plt.show()

"""## 8. Empirical cumulative distribution functions (Figure 4)

The ECDFs visual of the KS tests.

 sampleof  a fixed number of cells per slope class (stratified random sample) and  KS D values printed in each panel legend are computed in the next section.
"""

from matplotlib.lines import Line2D

methods       = ["ls_baseline", "ls_v1", "ls_v2"]
method_labels = ["Method BL", "Method F1", "Method F2"]
method_colors = ["black", "#1D5FA2", "#A03032"]
method_styles = ["-", "--", ":"]

classes = ["<9%", "9–22%", "22–55%", ">55%"]

# x-axis upper limit per slope class (chosen so the curves are readable)
xlims = {"<9%": 5, "9–22%": 25, "22–55%": 60, ">55%": 150}

# stratified random sample per class
sample_size_per_class = 300_000
rng = np.random.default_rng(42)

fig, axes = plt.subplots(2, 2, figsize=(11, 8))

for ax, sc in zip(axes.flat, classes):
    sub = df[df["slope_class"] == sc]
    n_class = len(sub)
    if n_class > sample_size_per_class:
        sub = sub.sample(sample_size_per_class, random_state=42)
    n = len(sub)

    for method, label, color, style in zip(methods, method_labels, method_colors, method_styles):
        vals = np.sort(sub[method].dropna().to_numpy())
        cdf = np.arange(1, len(vals) + 1) / len(vals)
        ax.plot(vals, cdf, color=color, linestyle=style, linewidth=1.2, label=label)

    # KS D values for the legend (computed on the same subsample)
    d_b_v1, _ = stats.ks_2samp(sub["ls_baseline"], sub["ls_v1"])
    d_b_v2, _ = stats.ks_2samp(sub["ls_baseline"], sub["ls_v2"])
    d_v1_v2, _ = stats.ks_2samp(sub["ls_v1"],     sub["ls_v2"])

    ax.set_xlim(0, xlims[sc])
    ax.set_ylim(0, 1.02)
    ax.set_title(f"({chr(97 + classes.index(sc))}) Slope class {sc}")
    ax.set_xlabel("LS factor")
    ax.set_ylabel("Cumulative probability")
    ax.grid(True, linestyle="--", linewidth=0.4, alpha=0.5)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    txt = (
        f"D (BL, F1) = {d_b_v1:.3f}\n"
        f"D (BL, F2) = {d_b_v2:.3f}\n"
        f"D (F1, F2) = {d_v1_v2:.3f}\n"
        f"n = {n:,}"
    )
    ax.text(0.97, 0.45, txt, transform=ax.transAxes,
            fontsize=9, ha="right", va="top",
            bbox=dict(boxstyle="round,pad=0.4", facecolor="white",
                      edgecolor="lightgrey", linewidth=0.5))

    ax.legend(loc="lower right", fontsize=9, frameon=False)

plt.tight_layout()
fig.savefig(r"W:\ls_ecdfs.png", dpi=600, bbox_inches="tight", facecolor="white")
plt.show()

"""## 9. Kolmogorov–Smirnov tests

Two-sample KS tests for the three pairwise comparisons. Done both globally (on a 500k random subsample of the whole dataframe) and per slope class.

Given the very large sample sizes the p-values are essentially zero everywhere, so the D statistic is theeffect size that matters
"""

# Subsample because ks_2samp gets slow on >25 million points
df_test = df.sample(500_000, random_state=42)

# Global KS tests (whole study area)
print("=" * 50)
print("Global KS tests")
print("=" * 50)

for name, a, b in [
    ("baseline vs v1", df_test["ls_baseline"], df_test["ls_v1"]),
    ("baseline vs v2", df_test["ls_baseline"], df_test["ls_v2"]),
    ("v1 vs v2",       df_test["ls_v1"],       df_test["ls_v2"]),
]:
    res = stats.ks_2samp(a, b, alternative="two-sided", method="auto")
    print(f"{name:<20}  D = {res.statistic:.4f}   p = {res.pvalue:.3e}")

# Per slope class
classes = ["<9%", "9–22%", "22–55%", ">55%"]
ks_results = []

for sc in classes:
    sub = df_test[df_test["slope_class"] == sc]

    comparisons = [
        ("baseline_vs_v1", sub["ls_baseline"], sub["ls_v1"]),
        ("baseline_vs_v2", sub["ls_baseline"], sub["ls_v2"]),
        ("v1_vs_v2",       sub["ls_v1"],       sub["ls_v2"]),
    ]

    for comp_name, a, b in comparisons:
        res = stats.ks_2samp(a, b, alternative="two-sided", method="auto")
        ks_results.append({
            "slope_class": sc,
            "comparison":  comp_name,
            "n":           len(sub),
            "D":           res.statistic,
            "p_value":     res.pvalue,
        })

ks_df = pd.DataFrame(ks_results)
print(ks_df.to_string(index=False))

"""## 10. Mean LS factor vs slope gradient (Figure 2)

Two-panel plot showing how the mean LS factor evolves with slope for each method, with a difference plot underneath highlighting where F2 starts to exceed F1. The slope axis is binned in 1-percent increments and the mean (with IQR shaded) is plotted for every bin.

The vertical dotted lines mark the 9 / 22 / 55% class boundaries.
"""

# Bin the slope in 1% increments, compute mean + IQR per bin per method
slope_bins = np.arange(0, 91, 1)
df["slope_bin"] = pd.cut(df["slope_pct"], bins=slope_bins, right=False, labels=slope_bins[:-1])

agg = (
    df.groupby("slope_bin", observed=False)[["ls_baseline", "ls_v1", "ls_v2"]]
    .agg(["mean", lambda x: np.percentile(x, 25), lambda x: np.percentile(x, 75)])
)
agg.columns = [f"{c[0]}_{c[1]}" for c in agg.columns]
agg = agg.rename(columns=lambda c: c.replace("<lambda_0>", "q25").replace("<lambda_1>", "q75"))
agg = agg.reset_index()
agg["slope_bin"] = agg["slope_bin"].astype(float)

print(agg.head())

fig, (ax1, ax2) = plt.subplots(
    2, 1, figsize=(9, 6), sharex=True,
    gridspec_kw={"height_ratios": [3, 1.2]},
)

# Panel (a): mean LS factor per method with IQR shaded
methods_plot = [
    ("ls_baseline", "Method BL", "black",    "-"),
    ("ls_v1",       "Method F1", "#1D5FA2",  "--"),
    ("ls_v2",       "Method F2", "#A03032",  "-."),
]

for col, label, color, ls in methods_plot:
    ax1.plot(agg["slope_bin"], agg[f"{col}_mean"],
             color=color, linestyle=ls, linewidth=1.3, label=label)
    ax1.fill_between(agg["slope_bin"],
                     agg[f"{col}_q25"], agg[f"{col}_q75"],
                     color=color, alpha=0.12)

# Class boundary lines
for x in [9, 22, 55]:
    ax1.axvline(x, color="grey", linestyle=":", linewidth=0.8)

# Class labels at the top
class_label_x = [4, 15, 38, 72]
class_label_t = ["gentle", "moderate", "steep", "very steep"]
for x, t in zip(class_label_x, class_label_t):
    ax1.text(x, ax1.get_ylim()[1] * 0.95, t, ha="center", fontsize=9,
             style="italic", color="grey")

ax1.set_ylabel("Mean LS factor\n(with IQR shaded)")
ax1.set_ylim(0, 50)
ax1.legend(loc="upper left", frameon=False, fontsize=10)
ax1.set_title("(a)", loc="left", fontweight="bold")
ax1.spines["top"].set_visible(False)
ax1.spines["right"].set_visible(False)

# Panel (b): difference F2 - F1
delta = agg["ls_v2_mean"] - agg["ls_v1_mean"]
ax2.fill_between(agg["slope_bin"], 0, delta,
                 where=(delta >= 0), color="#A03032", alpha=0.5, label="F2 > F1")
ax2.fill_between(agg["slope_bin"], 0, delta,
                 where=(delta < 0),  color="#1D5FA2", alpha=0.5, label="F1 ≥ F2")
ax2.plot(agg["slope_bin"], delta, color="black", linewidth=0.8)

for x in [9, 22, 55]:
    ax2.axvline(x, color="grey", linestyle=":", linewidth=0.8)

ax2.set_xlabel("Slope (%)")
ax2.set_ylabel("Δ mean LS factor\n(F2 − F1)")
ax2.set_title("(b)", loc="left", fontweight="bold")
ax2.set_xlim(0, 90)
ax2.legend(loc="upper left", frameon=False, fontsize=9)
ax2.spines["top"].set_visible(False)
ax2.spines["right"].set_visible(False)

plt.tight_layout()
fig.savefig(r"W:\ls_slope_dependence.png",
            dpi=600, bbox_inches="tight", facecolor="white")
plt.show()

"""## 11. RUSLE input factor analysis (Table 2)

Spearman rank correlation between each RUSLE input factor and the final modelled soil loss (using the BL method as the reference for soil loss, as in the thesis), plus the coefficient of variation (CV) of each input factor.

This is done on a stratified random sample of 200'000 pixels so that the Spearman call doesn't blow up. The CV is computed on the full grid via `arcpy.GetRasterProperties_management()`
"""

# Pull all input factor rasters + the BL soil loss raster into one block extraction
r_raster   = arcpy.Raster(r_path)
k_raster   = arcpy.Raster(k_path)
ls_raster  = ls_baseline_r  # already loaded
c_raster   = arcpy.Raster(c_path)
ru_raster  = arcpy.Raster(ru_bl)

input_rasters = [r_raster, k_raster, ls_raster, c_raster, ru_raster]
labels        = ["R", "K", "LS", "C", "soil_loss"]

pbc_inputs = PixelBlockCollection(
    input_rasters,
    pixel_block_size=(512, 512),
    overlay_type="INTERSECTION",
    nodata_to_values=np.nan,
)

print("Number of blocks (y, x):", pbc_inputs.size)

# Loop through blocks, sample randomly from each one so the final dataframe stays small
sample_per_block = 200  # ~200 random cells per block
input_df_list = []

ny, nx = pbc_inputs.size
rng = np.random.default_rng(42)

for by in range(ny):
    for bx in range(nx):
        block = pbc_inputs[by, bx]
        arrs = [np.squeeze(b.getData()).astype("float64") for b in block]

        valid = np.ones_like(arrs[0], dtype=bool)
        for arr in arrs:
            valid &= ~np.isnan(arr)

        if valid.sum() == 0:
            continue

        # pick a small random subset to keep memory under control
        n_take = min(sample_per_block, int(valid.sum()))
        idx = rng.choice(int(valid.sum()), size=n_take, replace=False)

        block_data = {
            lab: arr[valid].ravel()[idx]
            for lab, arr in zip(labels, arrs)
        }
        input_df_list.append(pd.DataFrame(block_data))

input_df = pd.concat(input_df_list, ignore_index=True)

# Trim to exactly 200'000 if larger
if len(input_df) > 200_000:
    input_df = input_df.sample(200_000, random_state=42).reset_index(drop=True)

print("Input factor sample shape:", input_df.shape)
print(input_df.head())

#Spearman rank correlation: each input factor against soil loss
print("=" * 60)
print("Spearman rank correlation with modelled soil loss")
print("=" * 60)

corr_results = []
for fac in ["R", "K", "LS", "C"]:
    rho, p = stats.spearmanr(input_df[fac], input_df["soil_loss"])
    corr_results.append({"factor": fac, "spearman_rho": rho, "p_value": p})

corr_df = pd.DataFrame(corr_results)
print(corr_df.to_string(index=False))

# coefficientof variation(CV = std / mean * 100) per input factor
print("=" * 60)
print("Coefficient of variation per input factor (whole study area)")
print("=" * 60)

cv_results = []
for path, label in [
    (r_path,  "R"),
    (k_path,  "K"),
    (ls_baseline_path, "LS"),
    (c_path,  "C"),
]:
    mean_val = float(arcpy.GetRasterProperties_management(path, "MEAN").getOutput(0))
    std_val  = float(arcpy.GetRasterProperties_management(path, "STD").getOutput(0))
    cv = (std_val / mean_val) * 100 if mean_val != 0 else np.nan
    cv_results.append({"factor": label, "mean": mean_val, "std": std_val, "CV_pct": cv})

cv_df = pd.DataFrame(cv_results)
print(cv_df.to_string(index=False))

#final Table 2 combining the two
table2 = corr_df.merge(cv_df[["factor", "CV_pct"]], on="factor")
table2 = table2[["factor", "CV_pct", "spearman_rho"]]
print(table2.to_string(index=False))

"""## 12. Hotspot analysis (Section 4.4)

Hotspots are defined as cells exceeding 20 t ha⁻¹ yr⁻¹ (threshold from Meshesha et al. 2012; FAO & ITPS 2015 classifies anything >20 as high on tropical cropland).

Three steps here:

1. Binary hotspot raster per method (1 = hotspot, 0 = non-hotspot)
2. Combination raster using binary encoding so every pixel carries which method(s) flagged it
3. Jaccard similarity index between F1 and F2 hotspot layers
"""

HOT_THRESH = 20
OUTPUT_DIR = r"S:\group\ess_demand4restoration\bachelorThesisMarlena\outputshot"
os.makedirs(OUTPUT_DIR, exist_ok=True)

arcpy.env.workspace = r"S:\group\ess_demand4restoration\bachelorThesisMarlena"
arcpy.env.overwriteOutput = True

NAME_BL = "blloss_clip"
NAME_V1 = "F1loss_clip"
NAME_V2 = "F2los_clip"

print("Creating binary hotspot rasters...")

r_bl = Raster(NAME_BL)
r_v1 = Raster(NAME_V1)
r_v2 = Raster(NAME_V2)

hot_bl = Con(r_bl >= HOT_THRESH, 1, 0)
hot_v1 = Con(r_v1 >= HOT_THRESH, 1, 0)
hot_v2 = Con(r_v2 >= HOT_THRESH, 1, 0)

path_hot_bl = os.path.join(OUTPUT_DIR, "Hotspot_Baseline.tif")
path_hot_v1 = os.path.join(OUTPUT_DIR, "Hotspot_V1_McCool.tif")
path_hot_v2 = os.path.join(OUTPUT_DIR, "Hotspot_V2_Nearing.tif")

hot_bl.save(path_hot_bl); print("  Saved: Hotspot_Baseline.tif")
hot_v1.save(path_hot_v1); print("  Saved: Hotspot_V1_McCool.tif")
hot_v2.save(path_hot_v2); print("  Saved: Hotspot_V2_Nearing.tif")

"""### Combination raster

Binary encoding so every unique combination of method-agreements gets a unique pixel value. Useful for the consensus / partial agreement map (Figure 11 in the appendix).

```
0 = none
1 = V2 only      (Nearing unique — steep slope signal)
2 = V1 only      (McCool unique)
3 = V1 + V2      (both D&G agree, Moore misses)
4 = Baseline only
5 = Baseline + V2
6 = Baseline + V1
7 = all agree    (full consensus)
```
"""

print("Creating combination map...")

hot_bl = Raster(path_hot_bl)
hot_v1 = Raster(path_hot_v1)
hot_v2 = Raster(path_hot_v2)

combo = (hot_bl * 4) + (hot_v1 * 2) + (hot_v2 * 1)

path_combo = os.path.join(OUTPUT_DIR, "Hotspot_Combination.tif")
combo.save(path_combo)
print("Saved:", path_combo)

"""### Jaccard similarity (F1 vs F2)

Jaccard = |F1 ∩ F2| / |F1 ∪ F2|. Quantifies how much the two variant hotspot layers overlap. The thesis reports 91.7% agreement, with 6.7% of cells flagged only by F2 (steep-slope detections that F1 misses).
"""

print("Calculating Jaccard similarity...")

hot_v1 = Raster(path_hot_v1)
hot_v2 = Raster(path_hot_v2)

# Intersection: both V1 and V2 are hotspot
intersection = Con((hot_v1 == 1) & (hot_v2 == 1), 1, 0)
# Union: either V1 or V2 is hotspot
union_r = Con((hot_v1 == 1) | (hot_v2 == 1), 1, 0)
# Cells V2 flags but V1 misses
missed_r = Con((hot_v2 == 1) & (hot_v1 == 0), 1, 0)

# Mean of a binary raster = fraction of 1s
inter_mean  = float(arcpy.GetRasterProperties_management(intersection, "MEAN").getOutput(0))
union_mean  = float(arcpy.GetRasterProperties_management(union_r,      "MEAN").getOutput(0))
v2_mean     = float(arcpy.GetRasterProperties_management(hot_v2,       "MEAN").getOutput(0))
missed_mean = float(arcpy.GetRasterProperties_management(missed_r,     "MEAN").getOutput(0))

jaccard    = inter_mean / union_mean if union_mean > 0 else 0
missed_pct = (missed_mean / v2_mean) * 100 if v2_mean > 0 else 0

# Hotspot coverage per formulation
pct_bl = float(arcpy.GetRasterProperties_management(Raster(path_hot_bl), "MEAN").getOutput(0)) * 100
pct_v1 = float(arcpy.GetRasterProperties_management(hot_v1, "MEAN").getOutput(0)) * 100
pct_v2 = v2_mean * 100

print("\n" + "=" * 50)
print("JACCARD RESULTS")
print("=" * 50)
print(f"\nHotspot coverage (>{HOT_THRESH} t/ha/yr):")
print(f"  Baseline (Moore):  {pct_bl:.1f}%")
print(f"  V1 (McCool):       {pct_v1:.1f}%")
print(f"  V2 (Nearing):      {pct_v2:.1f}%")
print(f"\nJaccard V1 vs V2:              {jaccard:.4f}")
print(f"V2 hotspots missed by V1:      {missed_pct:.1f}%")

# Save the missed-by-F1 raster (for the appendix map showing what F1 misses)
path_missed = os.path.join(OUTPUT_DIR, "Hotspot_MissedByMcCool.tif")
missed_r.save(path_missed)

# Save numerical results to text
with open(os.path.join(OUTPUT_DIR, "jaccard_results.txt"), "w") as f:
    f.write("JACCARD SIMILARITY\n")
    f.write(f"Threshold: >{HOT_THRESH} t/ha/yr\n\n")
    f.write(f"Baseline hotspot %:   {pct_bl:.2f}%\n")
    f.write(f"V1 McCool hotspot %:  {pct_v1:.2f}%\n")
    f.write(f"V2 Nearing hotspot %: {pct_v2:.2f}%\n\n")
    f.write(f"Jaccard V1 vs V2:     {jaccard:.4f}\n")
    f.write(f"V2 missed by V1:      {missed_pct:.1f}%\n")
print("Saved: jaccard_results.txt")

"""## 13. Hotspot overlap with population density (Figure 9)

WorldPop 2020 1 km population density classes (very low ≤20, low ≤200, moderate ≤600, high >600 p/km²), reclassified to match the consensus hotspot raster and then summarised as percentage of total hotspot area falling in each density class.

This is the bar chart in Figure 9 of the thesis.
"""

# Resample population to match hotspot grid (nearest neighbour since it's a class map)
pop_raster = Raster(pop_path)

# Reclassify population density into 4 categories
pop_class = Con(pop_raster <= 20,  1,
            Con(pop_raster <= 200, 2,
            Con(pop_raster <= 600, 3, 4)))

path_pop_class = os.path.join(OUTPUT_DIR, "PopDensity_Classes.tif")
pop_class.save(path_pop_class)
print("Saved:", path_pop_class)

# Consensus hotspot = all 3 methods flag it
consensus = Con((hot_bl == 1) & (hot_v1 == 1) & (hot_v2 == 1), 1, 0)
path_consensus = os.path.join(OUTPUT_DIR, "Hotspot_Consensus.tif")
consensus.save(path_consensus)

#for each population class, count hotspot cells
tab = arcpy.sa.TabulateArea(
    in_zone_data=path_pop_class,
    zone_field="Value",
    in_class_data=path_consensus,
    class_field="Value",
    out_table=os.path.join(OUTPUT_DIR, "hotspot_by_popclass.dbf"),
    processing_cell_size=30,
)
print("Tabulated.")

#tabulated area DBF back into pandas
tab_arr = arcpy.da.TableToNumPyArray(
    os.path.join(OUTPUT_DIR, "hotspot_by_popclass.dbf"),
    "*",
)
tab_df = pd.DataFrame(tab_arr)
print(tab_df)

#percentages of pop class per hotspot = table
pop_class_labels = {1: "Very Low (≤20 p/km²)",
                    2: "Low (≤200 p/km²)",
                    3: "Moderate (≤600 p/km²)",
                    4: "High (>600 p/km²)"}

# `VALUE_1` column = hotspot cells in each population zone
tab_df["pop_label"] = tab_df["VALUE"].map(pop_class_labels)
total_hotspot_area = tab_df["VALUE_1"].sum()
tab_df["pct_of_hotspots"] = 100 * tab_df["VALUE_1"] / total_hotspot_area

print(tab_df[["pop_label", "VALUE_1", "pct_of_hotspots"]])

#Bar chart (Figure 9)
fig, ax = plt.subplots(figsize=(7, 4))

order = [4, 3, 2, 1]  # high -> very low
tab_df_sorted = tab_df.set_index("VALUE").loc[order].reset_index()

bars = ax.barh(tab_df_sorted["pop_label"], tab_df_sorted["pct_of_hotspots"],
               color="#E8B98C", edgecolor="black", linewidth=0.5)

for bar, val in zip(bars, tab_df_sorted["pct_of_hotspots"]):
    ax.text(val + 0.5, bar.get_y() + bar.get_height() / 2,
            f"{val:.2f}%", va="center", fontsize=10)

ax.set_xlabel("Percentage of hotspot area (%)")
ax.set_ylabel("Population Density (p/km²)")
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.grid(axis="x", linestyle="--", linewidth=0.4, alpha=0.5)

plt.tight_layout()
fig.savefig(r"W:\hotspot_popdensity.png",
            dpi=600, bbox_inches="tight", facecolor="white")
plt.show()

"""## 14. Areal distribution of RUSLE soil loss classes (Figure 12)

Six standard soil loss classes (Negligible, Low, Moderate, High, Very High, Severe) computed per method. The thesis uses this as Figure 12 in the appendix to show how methods redistribute pixels between classes.
"""

#soil loss rusle rasters ito dataframe
raster_list_loss = [
    arcpy.Raster(ru_bl),
    arcpy.Raster(ru_v1),
    arcpy.Raster(ru_v2),
]

pbc_loss = PixelBlockCollection(
    raster_list_loss,
    pixel_block_size=(512, 512),
    overlay_type="INTERSECTION",
    nodata_to_values=np.nan,
)

loss_df_list = []
ny, nx = pbc_loss.size

for by in range(ny):
    for bx in range(nx):
        block = pbc_loss[by, bx]
        arrs = [np.squeeze(b.getData()).astype("float64") for b in block]

        valid = ~np.isnan(arrs[0]) & ~np.isnan(arrs[1]) & ~np.isnan(arrs[2])
        if valid.sum() == 0:
            continue

        loss_df_list.append(pd.DataFrame({
            "loss_bl": arrs[0][valid].ravel(),
            "loss_v1": arrs[1][valid].ravel(),
            "loss_v2": arrs[2][valid].ravel(),
        }))

loss_df = pd.concat(loss_df_list, ignore_index=True)
print(loss_df.shape)
print(loss_df.describe())

#classify into the 6 erosion classes
loss_bins   = [0, 1, 5, 10, 20, 50, np.inf]
loss_labels = ["Negligible (<1)", "Low (1–5)", "Moderate (5–10)",
               "High (10–20)", "Very High (20–50)", "Severe (>50)"]

for col, suf in [("loss_bl", "bl"), ("loss_v1", "v1"), ("loss_v2", "v2")]:
    loss_df[f"class_{suf}"] = pd.cut(loss_df[col], bins=loss_bins,
                                     labels=loss_labels, right=False)

# Percentage per class per method
class_pct = pd.DataFrame({
    "BL":  loss_df["class_bl"].value_counts(normalize=True).sort_index() * 100,
    "F1":  loss_df["class_v1"].value_counts(normalize=True).sort_index() * 100,
    "F2":  loss_df["class_v2"].value_counts(normalize=True).sort_index() * 100,
})
print(class_pct)

#bar chart (Figure 12)
fig, ax = plt.subplots(figsize=(9, 5))

y_pos = np.arange(len(loss_labels))
bar_h = 0.27

bars_bl = ax.barh(y_pos - bar_h, class_pct["BL"], height=bar_h, label="BL Soil Loss", color="#1a1a1a")
bars_f1 = ax.barh(y_pos,         class_pct["F1"], height=bar_h, label="F1 Soil Loss", color="#6e6e6e")
bars_f2 = ax.barh(y_pos + bar_h, class_pct["F2"], height=bar_h, label="F2 Soil Loss", color="#bdbdbd")

# Labels at end of each bar
for bars in [bars_bl, bars_f1, bars_f2]:
    for bar in bars:
        w = bar.get_width()
        ax.text(w + 0.2, bar.get_y() + bar.get_height() / 2,
                f"{w:.2f}%", va="center", fontsize=8)

ax.set_yticks(y_pos)
ax.set_yticklabels(loss_labels)
ax.set_xlabel("Percentage of study area (%)")
ax.set_title("Area per RUSLE Erosion Class — BL vs F1 vs F2", fontsize=11)
ax.legend(loc="lower right", frameon=False, fontsize=9)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.grid(axis="x", linestyle="--", linewidth=0.4, alpha=0.5)

plt.tight_layout()
fig.savefig(r"W:\soilloss_classes.png",
            dpi=600, bbox_inches="tight", facecolor="white")
plt.show()

"""---

End of analysis. Output files are saved to `S:/group/ess_demand4restoration/bachelorThesisMarlena/outputshot/` (rasters) and `W:/` (figures).
"""